# lintangbirdas/go-chat:v1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-chat
spec:
  selector:
    matchLabels:
      app: go-chat
  template:
    metadata:
      labels:
        app: go-chat
    spec:
      containers:
      - name: go-chat
        image: docker.io/lintangbirdas/go-chat:v1
        env:
          - name: REDIS_ADDRESS
            value: redis-headless.redis:6379
          - name: REDIS_PASSWORD
            value: lintang
          - name: POSTGRES_USERNAME
            value: lintang
          - name: POSTGRES_PASSWORD
            value: lintang
          - name: POSTGRES_HOST
            value: my-pgsql-cluster-rw.pg
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-chat
spec:
  selector:
    app: go-chat
  ports:
  - port: 8080
    targetPort: 8080
