---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-server-ingress
  namespace: chat
spec:
  ingressClassName: nginx
  rules:
  - host: ""
    http:
      paths:
      - pathType: Prefix
        path: /nginx
        backend:
          service:
            name:  nginx-project
            port:
              number: 80
      - pathType: Prefix
        path: /chat 
        backend:
          service:
            name: go-chat
            port:
              number: 8080