---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pg
  namespace: argocd
 
spec:
  project: default
  source:
    repoURL:  https://cloudnative-pg.io/charts
    targetRevision: 0.20.2
    chart:  cloudnative-pg/cloudnative-pg
    helm:
      releaseName: pg-operator
      passCredentials: false
 
  destination:
    server: https://kubernetes.default.svc
    namespace: chat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

